app = "predecessor-tournament-system" 
primary_region = "syd"

[build]

[http_service]
  internal_port = 4000
  force_https = true

[env]
  PHX_HOST = "predecessor-tournament-system.fly.dev"
  PHX_SERVER = "true"
  MIX_ENV = "prod"