# fly.toml app configuration file generated for predecessor-draft-phoenix

app = "predecessor-draft-phoenix"
primary_region = "iad"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true

  [http_service.checks]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[env]
  PHX_HOST = "predecessor-draft-phoenix.fly.dev"
  PHX_SERVER = "true"
  MIX_ENV = "prod"
  ECTO_IPV6 = "false"
  POOL_SIZE = "10"

[deploy]
  release_command = "/app/bin/predecessor_draft eval \"PredecessorDraft.Release.migrate\""