services:
  - type: web
    name: predecessor-draft-phoenix
    runtime: docker
    repo: https://github.com/Sitting-in-a-towel/predecessor-tournament-system
    branch: main
    rootDir: phoenix_draft
    dockerfilePath: Dockerfile
    envVars:
      - key: MIX_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: predecessor-tournament-db
          property: connectionString
      - key: SECRET_KEY_BASE
        value: 4350d403df7c38dc965fecdc9fbc2780
      - key: PHX_HOST
        value: predecessor-draft-phoenix.onrender.com
      - key: PHX_SERVER
        value: true
      - key: POOL_SIZE
        value: 10
      - key: RELEASE_TMP
        value: /tmp
      - key: ECTO_IPV6
        value: false